### PR TITLE
Status Bar Fixed

### PR DESCRIPTION
**Pull request by Redeem-Grimm-Satoshi**
**Changed from **navigationBarColor to statusBarColor** ( and it worked )

**Added **windowsLightStatusBar** ( with boolean value: [true] so that status bar doens't become opaque

**Light and Dark theme colors implemented

### CODE REVIEW

**Comment by maprehensive** [comment]
@Redeem-Grimm-Satoshi Thanks! 
Screenshots for the results can help reviewers immediately see results. 
I'm having trouble reviewing the PR, have asked for help to review code.

**Comment by Redeem-Grimm-Satoshi** [comment]
@maprehensive thanks, let send screenshots

**Comment by wbrunette** [comment]
I tried these changes on an emulator and when I entered dark mode it did not seem to work. Perhaps once you send screenshots you will have identified the issue.

**Comment by Redeem-Grimm-Satoshi** [comment]
Yes I'm working on that, using android 9 and seems to have some issues with darkmode.

**Comment by Redeem-Grimm-Satoshi** [comment]
@wbrunette I forgot darkmode is made available from API 29 and higher and my android devices are Android 9 ( API 28 ),  that's where I had issues. Switching to Android 10 so I fix the issues and send the final PR

**Pull request closed without merging**
