### PR TITLE
Extended Color Palette

### PR DESCRIPTION
**Pull request by Redeem-Grimm-Satoshi**
Extended color palette to meet material guidelines.

### CODE REVIEW

**Comment by Redeem-Grimm-Satoshi** [comment]
@wbrunette Did some update on the color palette

**Review by wbrunette — APPROVED** [review]

**Comment by wbrunette** [comment]
@Cveman1 can you review the color hex values to make sure they are accurate then I will merge.

**Review by Cveman1 — COMMENTED** [review]
All the colour codes are pretty much what we discussed on the Google slides. Good to go @wbrunette

**Comment by maprehensive** [comment]
Ben to review on branch Outreachy 23

**Pull request merged**
